### ISSUE TITLE
Calibration files not found

### ISSUE THREAD

**Issue by hebeling** [Keck-DataReductionPipelines/KcwiDRP#2]
Kcwi_prep works once the file root is provided explicitly but everything beyond stage 1 of the pipeline runs into problems. Specifically, the DRP does not appear to create / find the necessary calibration files:

 41/ 41     88 2 2 TUP  0 10 000 Med BM   KBlu   5000.0 2458573.138   10.0 object          88 308.59116667  25.06380556    90.00  1.370  wolf1346
KCWI_STAGE2DARK      [INFO 1 ] input reduced image: /Volumes/T01/d1/keck/kcwi/raw/mar19/redux/kb190330_00088_int.fits
KCWI_DO_DARK         [INFO 1 ] DS Test (drk?, msig, tsig): NO    0.1864  0.2841
KCWI_STAGE2DARK      [WARNING] cannot associate with any master dark: kb190330_00088_int.fits
KCWI_STAGE2DARK      [INFO 1 ] scattered light subtracted
KCWI_WRITE_IMAGE     [INFO 1 ] wrote image file: /Volumes/T01/d1/keck/kcwi/raw/mar19/redux/kb190330_00088_mskd.fits
KCWI_WRITE_IMAGE     [INFO 1 ] wrote image file: /Volumes/T01/d1/keck/kcwi/raw/mar19/redux/kb190330_00088_vard.fits
KCWI_WRITE_IMAGE     [INFO 1 ] wrote image file: /Volumes/T01/d1/keck/kcwi/raw/mar19/redux/kb190330_00088_intd.fits

KCWI_STAGE2DARK      [INFO 1 ] run time in seconds:        117.51911
KCWI_STAGE2DARK      [INFO 1 ] finished on Fri Apr 12 11:57:07 2019
IDL> kcwi_stage3geom
% Compiled module: KCWI_STAGE3GEOM.
fatal: Not a git repository (or any of the parent directories): .git
KCWI_READ_PROC       [INFO 1 ] Master proc file: /Volumes/T01/d1/keck/kcwi/raw/mar19/redux/kcwi.proc
KCWI_READ_PROC       [INFO 1 ] Fri Apr 12 11:57:15 2019
KCWI_STAGE3GEOM      [INFO 1 ] Number of input images:       41

  1/ 41     27 2 2 TUP  0 10 000 Med BM   KBlu   5000.0 2458572.590   36.7 dflat           27  58.00000000  45.00000000     0.00  1.410
KCWI_STAGE3GEOM      [INFO 1 ] input 2-D image: /Volumes/T01/d1/keck/kcwi/raw/mar19/redux/kb190330_00027_intd.fits
KCWI_STAGE3GEOM      [WARNING] missing calibration file(s) for: /Volumes/T01/d1/keck/kcwi/raw/mar19/redux/kb190330_00027_intd.fits

The AAAREADME file provides no information that would help me solve these problems - or did I miss it? All my original FITS files are in the same directory, and I specified "." as the "calibration directory" during the kcwi_prep phase.

Thanks in advance!

Harald

**Comment by lucarizzi** [comment]
A few questions:
1- Are you using the original file names or the KOA generated file names? 
2- After you run kcwi_prep, there are some diagnostic files that identify the file types. One of them is what.list. Could you upload it here?

**Comment by hebeling** [comment]
On Mon, Apr 15, 2019 at 7:27 AM lucarizzi <notifications@github.com> wrote:

> A few questions:
> 1- Are you using the original file names or the KOA generated file names?
>

Original file names. The KOA file names cause kiwi_prep to fail instantly
because it takes the root file name from the FITS headers. The latter of
course contain the original file names which do not match the KOA naming
convention.


> 2- After you run kcwi_prep, there are some diagnostic files that identify
> the file types. One of them is what.list. Could you upload it here?
>
No file name what.list exists in my data directory - nothing in the redux
directory either. No result returned by  find . -name "*what*" . Could it
have a different name?

Thanks!

Harald

**Comment by lucarizzi** [comment]
In this case, can you send the result of running just the kcwi_prep? that produces a file called a proc table

**Comment by hebeling** [comment]
kcwi.proc is attached.

A little more background, in the hope that it helps track down the cause of
the problem. I set up for KCWI data reduction by sourcing a file that
contains these two lines:

setenv IDL_PATH "+/Users/ebeling/soft/kcwi/KcwiDRP-master:<IDL_DEFAULT>"

setenv IDL_STARTUP /Users/ebeling/soft/kcwi/KcwiDRP-master/startup.pro


I then start IDL in the directory that contains all raw data and issue

kcwi_prep


which produces the following output:


IDL> kcwi_prep

% Compiled module: KCWI_PREP.

% Compiled module: KCWI_PPAR__DEFINE.

% Compiled module: STRUCT_INIT.

% Compiled module: GETTOK.

% Compiled module: KCWI_EXPAND_DIR.

% Compiled module: HEADFITS.

% Compiled module: FXPOSIT.

% Compiled module: MRD_HREAD.

% Compiled module: SXPAR.

% Compiled module: KCWI_PRINT_INFO.

% Compiled module: KCWI_VERIFY_PPAR.

KCWI_PREP            [INFO 1 ] Input image file prefix: kb190331_

% Compiled module: KCWI_GET_DIGITS.

% Compiled module: FDECOMP.

KCWI_PREP            [INFO 1 ] number of digits in image numbers:        5

% Compiled module: FILESTAMP.

% Compiled module: TIMESTR.

% Compiled module: KCWI_DRP_VERSION.

fatal: Not a git repository (or any of the parent directories): .git

% Compiled module: STRN.

% Compiled module: KCWI_READ_CFGS.

% Compiled module: KCWI_CFG__DEFINE.

% Compiled module: KCWI_READ_CFG.

% Compiled module: RADEC_PARSE.

% Compiled module: STRSPLIT.

% Compiled module: KCWI_PARSE_DATES.

% Compiled module: JULDAY.

KCWI_PREP            [INFO 1 ] Number of raw input images:            1

% Compiled module: KCWI_PRINT_CFGS.

% Compiled module: KCWI_VERIFY_CFG.

% Compiled module: CALDAT.

KCWI_PREP            [WARNING] no object/cal images to process

KCWI_PREP            [INFO 1 ] Number of local images in calibration pool:
    1

% Compiled module: KCWI_FIND_STDS.

KCWI_FIND_STDS       [INFO 1 ] Mon Apr 15 12:39:42 2019

% Compiled module: KCWI_VERIFY_DIRS.

KCWI_FIND_STDS       [INFO 1 ] Found this many standard star observations:
  0

KCWI_PREP            [WARNING] no standard star images found

KCWI_PREP            [INFO 1 ] processing 0 images

% Compiled module: KCWI_GROUP_BIASES.

KCWI_GROUP_BIASES    [WARNING] no bias groups with >= :        5 images.

KCWI_GROUP_BIASES    [INFO 1 ] Number of bias groups:        0

% Compiled module: KCWI_GROUP_DARKS.

KCWI_GROUP_DARKS     [WARNING] no dark frames found

% Compiled module: KCWI_GROUP_FLATS.

KCWI_GROUP_FLATS     [WARNING] no flat frames found

% Compiled module: KCWI_GROUP_DGEOM.

KCWI_GROUP_DGEOM     [INFO 1 ] no direct arcs found

KCWI_GROUP_DGEOM     [INFO 1 ] no direct arcbars found

% Compiled module: KCWI_GROUP_GEOM.

KCWI_GROUP_GEOM      [ERROR  ] no arcs found!

KCWI_GROUP_GEOM      [ERROR  ] no bars found!

KCWI_PREP            [INFO 1 ] Number of standard star images:            0

% Compiled module: KCWI_WRITE_PPAR.

KCWI_WRITE_PPAR      [INFO 1 ] archived existing ppar file:
/Volumes/T01/d1/keck/kcwi/raw/mar19/redux/kcwi.ppar

KCWI_WRITE_PPAR      [INFO 1 ] kcwi.ppar written in directory
/Volumes/T01/d1/keck/kcwi/raw/mar19/redux/

KCWI_PREP            [INFO 1 ] Writing automatic cal associations to:
/Volumes/T01/d1/keck/kcwi/raw/mar19/redux/kcwi.proc

KCWI_PREP            [INFO 1 ] Edit this file to customize cal associations


KCWI_PREP            [INFO 1 ] CONFIGURATION CALIBRATION REPORT

KCWI_PREP            [WARNING] No bias groups found

KCWI_PREP            [WARNING] No dark groups found

KCWI_PREP            [WARNING] No flat groups found

KCWI_PREP            [WARNING] No geom groups found

KCWI_PREP            [WARNING] No standard star images found


KCWI_PREP            [INFO 1 ] run time in seconds:        2.5140100

KCWI_PREP            [INFO 1 ] finished on Mon Apr 15 12:39:42 2019

As you can see, kcwi_prep processed only a single file, because it used
kb190331 as the file prefix. Why it uses this prefix is unclear to me,
given that the raw data directory contains dozens of files starting in
kb190330_:

[marvin:kcwi/raw/mar19] ebeling% ls *fits

kb190330_00002.fits kb190330_00017.fits kb190330_00032.fits
kb190330_00047.fits kb190330_00062.fits kb190330_00077.fits

kb190330_00003.fits kb190330_00018.fits kb190330_00033.fits
kb190330_00048.fits kb190330_00063.fits kb190330_00078.fits

kb190330_00004.fits kb190330_00019.fits kb190330_00034.fits
kb190330_00049.fits kb190330_00064.fits kb190330_00079.fits

kb190330_00005.fits kb190330_00020.fits kb190330_00035.fits
kb190330_00050.fits kb190330_00065.fits kb190330_00080.fits

kb190330_00006.fits kb190330_00021.fits kb190330_00036.fits
kb190330_00051.fits kb190330_00066.fits kb190330_00081.fits

kb190330_00007.fits kb190330_00022.fits kb190330_00037.fits
kb190330_00052.fits kb190330_00067.fits kb190330_00082.fits

kb190330_00008.fits kb190330_00023.fits kb190330_00038.fits
kb190330_00053.fits kb190330_00068.fits kb190330_00083.fits

kb190330_00009.fits kb190330_00024.fits kb190330_00039.fits
kb190330_00054.fits kb190330_00069.fits kb190330_00084.fits

kb190330_00010.fits kb190330_00025.fits kb190330_00040.fits
kb190330_00055.fits kb190330_00070.fits kb190330_00085.fits

kb190330_00011.fits kb190330_00026.fits kb190330_00041.fits
kb190330_00056.fits kb190330_00071.fits kb190330_00086.fits

kb190330_00012.fits kb190330_00027.fits kb190330_00042.fits
kb190330_00057.fits kb190330_00072.fits kb190330_00087.fits

kb190330_00013.fits kb190330_00028.fits kb190330_00043.fits
kb190330_00058.fits kb190330_00073.fits kb190330_00088.fits

kb190330_00014.fits kb190330_00029.fits kb190330_00044.fits
kb190330_00059.fits kb190330_00074.fits kb190331_00001.fits

kb190330_00015.fits kb190330_00030.fits kb190330_00045.fits
kb190330_00060.fits kb190330_00075.fits kf190330_000001.fits

kb190330_00016.fits kb190330_00031.fits kb190330_00046.fits
kb190330_00061.fits kb190330_00076.fits

Assuming that the pipeline cannot handle data from more than one day, I
thus explicitly specify the fileroot:

kcwi_prep,froot='kb190330_'

which appears to have the desired effect:

% Compiled module: KCWI_PPAR__DEFINE.

% Compiled module: STRUCT_INIT.

% Compiled module: GETTOK.

% Compiled module: KCWI_EXPAND_DIR.

% Compiled module: KCWI_PRINT_INFO.

% Compiled module: KCWI_VERIFY_PPAR.

KCWI_PREP            [INFO 1 ] Input image file prefix: kb190330_

% Compiled module: KCWI_GET_DIGITS.

% Compiled module: FDECOMP.

% Compiled module: HEADFITS.

% Compiled module: FXPOSIT.

% Compiled module: MRD_HREAD.

% Compiled module: SXPAR.

KCWI_PREP            [INFO 1 ] number of digits in image numbers:        5

% Compiled module: FILESTAMP.

% Compiled module: TIMESTR.

% Compiled module: KCWI_DRP_VERSION.

fatal: Not a git repository (or any of the parent directories): .git

% Compiled module: STRN.

% Compiled module: KCWI_READ_CFGS.

% Compiled module: KCWI_CFG__DEFINE.

% Compiled module: KCWI_READ_CFG.

% Compiled module: RADEC_PARSE.

% Compiled module: STRSPLIT.

% Compiled module: KCWI_PARSE_DATES.

% Compiled module: JULDAY.

KCWI_PREP            [INFO 1 ] Number of raw input images:           87

% Compiled module: KCWI_PRINT_CFGS.

% Compiled module: KCWI_VERIFY_CFG.

% Compiled module: CALDAT.

KCWI_PREP            [INFO 1 ] Number of local images in calibration pool:
  19

% Compiled module: KCWI_FIND_STDS.

KCWI_FIND_STDS       [INFO 1 ] Mon Apr 15 12:45:00 2019

% Compiled module: KCWI_VERIFY_DIRS.

% Compiled module: KCWI_STD_NAME.

KCWI_FIND_STDS       [INFO 1 ] Found this many standard star observations:
  7

KCWI_PREP            [INFO 1 ] processing 41 images

% Compiled module: KCWI_GROUP_BIASES.

% Compiled module: RANGEPAR.

% Compiled module: BADPAR.

% Compiled module: UNIQ.

% Compiled module: KCWI_WRITE_PPAR.

% FILE_DELETE: Removed file:
/Volumes/T01/d1/keck/kcwi/raw/mar19/redux/kb190330_00020_mbias.ppar.

KCWI_WRITE_PPAR      [INFO 1 ] deleted existing ppar file:
/Volumes/T01/d1/keck/kcwi/raw/mar19/redux/kb190330_00020_mbias.ppar

KCWI_WRITE_PPAR      [INFO 1 ] kb190330_00020_mbias.ppar written in
directory /Volumes/T01/d1/keck/kcwi/raw/mar19/redux/

KCWI_GROUP_BIASES    [INFO 1 ] removing :   1 bias groups with <   5 images.

KCWI_GROUP_BIASES    [INFO 1 ] Number of bias groups:        1

% Compiled module: KCWI_GROUP_DARKS.

KCWI_GROUP_DARKS     [WARNING] no dark frames found

% Compiled module: KCWI_GROUP_FLATS.

% Compiled module: KCWI_MATCH_CFG.

% Compiled module: GCIRC.

% FILE_DELETE: Removed file:
/Volumes/T01/d1/keck/kcwi/raw/mar19/redux/kb190330_00027_mflat.ppar.

KCWI_WRITE_PPAR      [INFO 1 ] deleted existing ppar file:
/Volumes/T01/d1/keck/kcwi/raw/mar19/redux/kb190330_00027_mflat.ppar

KCWI_WRITE_PPAR      [INFO 1 ] kb190330_00027_mflat.ppar written in
directory /Volumes/T01/d1/keck/kcwi/raw/mar19/redux/

% FILE_DELETE: Removed file:
/Volumes/T01/d1/keck/kcwi/raw/mar19/redux/kb190330_00039_mflat.ppar.

KCWI_WRITE_PPAR      [INFO 1 ] deleted existing ppar file:
/Volumes/T01/d1/keck/kcwi/raw/mar19/redux/kb190330_00039_mflat.ppar

KCWI_WRITE_PPAR      [INFO 1 ] kb190330_00039_mflat.ppar written in
directory /Volumes/T01/d1/keck/kcwi/raw/mar19/redux/

% FILE_DELETE: Removed file:
/Volumes/T01/d1/keck/kcwi/raw/mar19/redux/kb190330_00051_mflat.ppar.

KCWI_WRITE_PPAR      [INFO 1 ] deleted existing ppar file:
/Volumes/T01/d1/keck/kcwi/raw/mar19/redux/kb190330_00051_mflat.ppar

KCWI_WRITE_PPAR      [INFO 1 ] kb190330_00051_mflat.ppar written in
directory /Volumes/T01/d1/keck/kcwi/raw/mar19/redux/

KCWI_GROUP_FLATS     [INFO 1 ] Number of flat groups:        3

% Compiled module: KCWI_GROUP_DGEOM.

KCWI_GROUP_DGEOM     [INFO 1 ] no direct arcs found

KCWI_GROUP_DGEOM     [INFO 1 ] no direct arcbars found

% Compiled module: KCWI_GROUP_GEOM.

KCWI_GROUP_GEOM      [ERROR  ] no arcs found!

KCWI_GROUP_GEOM      [ERROR  ] no bars found!

KCWI_PREP            [INFO 1 ] Number of standard star images:            7

KCWI_WRITE_PPAR      [INFO 1 ] archived existing ppar file:
/Volumes/T01/d1/keck/kcwi/raw/mar19/redux/kcwi.ppar

KCWI_WRITE_PPAR      [INFO 1 ] kcwi.ppar written in directory
/Volumes/T01/d1/keck/kcwi/raw/mar19/redux/

KCWI_PREP            [INFO 1 ] Writing automatic cal associations to:
/Volumes/T01/d1/keck/kcwi/raw/mar19/redux/kcwi.proc

KCWI_PREP            [INFO 1 ] Edit this file to customize cal associations


  1/ 41     27 2 2 TUP  0 10 000 Med BM   KBlu   5000.0 2458572.590   36.7
dflat           27  58.00000000  45.00000000     0.00  1.410

KCWI_PREP            [INFO 1 ] master bias file = kb190330_00020_mbias.fits

KCWI_PREP            [INFO 1 ] master flat file = kb190330_00027_mflat.fits


  2/ 41     28 2 2 TUP  0 10 000 Med BM   KBlu   5000.0 2458572.591   36.7
dflat           28  58.00000000  45.00000000     0.00  1.410

KCWI_PREP            [INFO 1 ] master bias file = kb190330_00020_mbias.fits

KCWI_PREP            [INFO 1 ] master flat file = kb190330_00027_mflat.fits


  3/ 41     29 2 2 TUP  0 10 000 Med BM   KBlu   5000.0 2458572.592   36.7
dflat           29  58.00000000  45.00000000     0.00  1.410

KCWI_PREP            [INFO 1 ] master bias file = kb190330_00020_mbias.fits

KCWI_PREP            [INFO 1 ] master flat file = kb190330_00027_mflat.fits


and so on.

The following two steps (stage1 and 2) finishe without warnings but beyond
that the missing calibration error messages pop up.

Thanks for helping!

Harald

**Comment by lucarizzi** [comment]
Could you try to run the pipeline on a directory that only contains data from the 190330 data? Remove any reference to 190331. I am not sure how froot works and if it is implemented correctly.

I have your data on disk, and I have no problem running the pipeline, but I only have 190330.

The relevant line I get from running kcwi_prep is:

% Compiled module: JULDAY.
KCWI_PREP            [INFO 1 ] Number of raw input images:           65
% Compiled module: KCWI_PRINT_CFGS.

While you get:
% Compiled module: JULDAY.
KCWI_PREP            [INFO 1 ] Number of raw input images:            1
% Compiled module: KCWI_PRINT_CFGS.

**Comment by hebeling** [comment]
I did get the correct number of input images from kcwi_prep when I
specified the froot parameter. When I remove the one file from Mar 31 (as
you suggested) and do NOT specify froot, the output from kcwi_prep appears
unchanged (it again finds all 87 images from 03/30). I am now running
everything from scratch again, starting from "kcwi_prep" (no froot
supplied). It's making its way through L.A. Cosmic... Will report whether
this changes anything for stages 3 and beyond!

Mahalo,

Harald

**Comment by hebeling** [comment]
No change, I'm afraid:

IDL> kcwi_stage3geom

% Compiled module: KCWI_STAGE3GEOM.

fatal: Not a git repository (or any of the parent directories): .git

KCWI_READ_PROC       [INFO 1 ] Master proc file:
/Volumes/T01/d1/keck/kcwi/raw/mar19/redux/kcwi.proc

KCWI_READ_PROC       [INFO 1 ] Mon Apr 15 14:37:59 2019

KCWI_STAGE3GEOM      [INFO 1 ] Number of input images:       41


  1/ 41     27 2 2 TUP  0 10 000 Med BM   KBlu   5000.0 2458572.590   36.7
dflat           27  58.00000000  45.00000000     0.00  1.410

KCWI_STAGE3GEOM      [INFO 1 ] input 2-D image:
/Volumes/T01/d1/keck/kcwi/raw/mar19/redux/kb190330_00027_intd.fits

KCWI_STAGE3GEOM      [WARNING] missing calibration file(s) for:
/Volumes/T01/d1/keck/kcwi/raw/mar19/redux/kb190330_00027_intd.fits


  2/ 41     28 2 2 TUP  0 10 000 Med BM   KBlu   5000.0 2458572.591   36.7
dflat           28  58.00000000  45.00000000     0.00  1.410

KCWI_STAGE3GEOM      [INFO 1 ] input 2-D image:
/Volumes/T01/d1/keck/kcwi/raw/mar19/redux/kb190330_00028_intd.fits

KCWI_STAGE3GEOM      [WARNING] missing calibration file(s) for:
/Volumes/T01/d1/keck/kcwi/raw/mar19/redux/kb190330_00028_intd.fits


  3/ 41     29 2 2 TUP  0 10 000 Med BM   KBlu   5000.0 2458572.592   36.7
dflat           29  58.00000000  45.00000000     0.00  1.410

KCWI_STAGE3GEOM      [INFO 1 ] input 2-D image:
/Volumes/T01/d1/keck/kcwi/raw/mar19/redux/kb190330_00029_intd.fits

KCWI_STAGE3GEOM      [WARNING] missing calibration file(s) for:
/Volumes/T01/d1/keck/kcwi/raw/mar19/redux/kb190330_00029_intd.fits

and so on... until

 40/ 41     87 2 2 TUP  0 10 000 Med BM   KBlu   5000.0 2458573.136   10.0
object          87 308.59116667  25.06380556    90.01  1.390  wolf1346

KCWI_STAGE3GEOM      [INFO 1 ] input 2-D image:
/Volumes/T01/d1/keck/kcwi/raw/mar19/redux/kb190330_00087_intd.fits

KCWI_STAGE3GEOM      [WARNING] missing calibration file(s) for:
/Volumes/T01/d1/keck/kcwi/raw/mar19/redux/kb190330_00087_intd.fits


 41/ 41     88 2 2 TUP  0 10 000 Med BM   KBlu   5000.0 2458573.138   10.0
object          88 308.59116667  25.06380556    90.00  1.370  wolf1346

KCWI_STAGE3GEOM      [INFO 1 ] input 2-D image:
/Volumes/T01/d1/keck/kcwi/raw/mar19/redux/kb190330_00088_intd.fits

KCWI_STAGE3GEOM      [WARNING] missing calibration file(s) for:
/Volumes/T01/d1/keck/kcwi/raw/mar19/redux/kb190330_00088_intd.fits


KCWI_STAGE3GEOM      [INFO 1 ] run time in seconds:        3.1006720

KCWI_STAGE3GEOM      [INFO 1 ] finished on Mon Apr 15 14:38:00 2019

I don't even understand what it is looking for. What calibration files?

**Comment by hebeling** [comment]
Aloha Team KCWI,

Is there anything else I can provide to help with the investigation of this
problem? Not being able to reduce these data has a serious impact on a
paper we had largely written prior to our run and meant to submit as
soon as possible (my collaborator is moving to Europe and will have very
little time to work on wrapping this up after May).

I could come to Waimea and (with Keck HQ's permission) use the DERP setup
there, but that would really be a last-resort solution.

Thanks for your help!

Harald

**Comment by lucarizzi** [comment]
I am on travel until the end of the week. I will be able to look into this further when I get back to Waimea after Easter.

We can reduce your data on your computers there, and find a way to transfer the results to you, next week.

**Comment by hebeling** [comment]
Thank you, Luca!

The odds are that I am making some stupid mistake - after all, others have
managed to install this pipeline (I presume). I just cannot figure out what
it is...

Aloha,

Harald

**Comment by lucarizzi** [comment]
Hi Harald,
I think I found the problem with your data.
We actually discussed it briefly when you were here, but I think we both lost track of it.
Some of your calibration files don't have the correct header information. Specifically, there is a keyword called CALTYPE, and I am sure that if you look at your files it is probably set to unknown.

For that reason, and to reduce the data online, we created a short script that fixes the header. The script is still in the reduced data directory on our computers.

Here it is:
```
from astropy.io import fits

contbars = [11,30,42]
arclamps = [12,13, 31,32, 43,44]
flatlamps = [14,15,16,17,18,19, 33,34,35,36,37,38, 45,46,47,48,49,50]
bias = [20,21,22,23,24,25,26]

prefix = "kb190330"

for frame in contbars:
    file_name = "%s_%05d.fits" % (prefix, frame)
    fits.setval(file_name, 'CALTYPE', value='cbars')

for frame in arclamps:
    file_name = "%s_%05d.fits" % (prefix, frame)
    fits.setval(file_name, 'CALTYPE', value='arcflat')

for frame in flatlamps:
    file_name = "%s_%05d.fits" % (prefix, frame)
    fits.setval(file_name, 'CALTYPE', value='cflat')

for frame in bias:
    file_name = "%s_%05d.fits" % (prefix, frame)
    fits.setval(file_name, 'CALTYPE', value='dark')
```

Make sure that the file numbers at the top correspond to the actual calibrations, but it seems correct to me.

Maybe make a copy of your data, and then run this script on the raw data before you do any pipeline step, including kcwi_prep.

**Comment by hebeling** [comment]
Hi Luca,

I don't recall us discussing this issue but this does not make me any less
grateful. Mahalo nui!

Will run this right away and report whether it fixes the problem...

Aloha,

Harald

**Comment by hebeling** [comment]
Hi Luca,

I think the earlier issue ("missing" calibration files) is now resolved,
but the DRP still crashes for me at stage 4:

IDL> kcwi_stage4flat

% Compiled module: KCWI_STAGE4FLAT.

fatal: Not a git repository (or any of the parent directories): .git

KCWI_READ_PROC       [INFO 1 ] Master proc file:
/Volumes/T01/d1/keck/kcwi/raw/mar19/redux/kcwi.proc

KCWI_READ_PROC       [INFO 1 ] Wed Apr 24 13:11:32 2019

KCWI_STAGE4FLAT      [INFO 1 ] Number of input images:       68


  1/ 68     11 2 2 ALL  1 10 000 Med BM   KBlu   5000.0 2458572.578    1.2
cbarsContin     11  58.00000000  45.00000000     0.00  1.410

KCWI_STAGE4FLAT      [INFO 1 ] input reduced image:
/Volumes/T01/d1/keck/kcwi/raw/mar19/redux/kb190330_00011_intd.fits

% Compiled module: FXMOVE.

% Compiled module: MATCH.

% Compiled module: MRD_STRUCT.

KCWI_STAGE4FLAT      [INFO 1 ] flat file =
/Volumes/T01/d1/keck/kcwi/raw/mar19/redux/kb190330_00014_mflat.fits

KCWI_STAGE4FLAT      [INFO 1 ] geom file =
/Volumes/T01/d1/keck/kcwi/raw/mar19/redux/kb190330_00011_geom.fits

KCWI_STAGE4FLAT      [INFO 1 ] skipping flattening of dark/arc/bars/direct
image


  2/ 68     12 2 2 ALL  1 10 000 Med BM   KBlu   5000.0 2458572.578   15.0
arcFeAr         12  58.00000000  45.00000000     0.00  1.410

KCWI_STAGE4FLAT      [INFO 1 ] input reduced image:
/Volumes/T01/d1/keck/kcwi/raw/mar19/redux/kb190330_00012_intd.fits

KCWI_STAGE4FLAT      [INFO 1 ] flat file =
/Volumes/T01/d1/keck/kcwi/raw/mar19/redux/kb190330_00014_mflat.fits

KCWI_STAGE4FLAT      [INFO 1 ] geom file =
/Volumes/T01/d1/keck/kcwi/raw/mar19/redux/kb190330_00011_geom.fits

KCWI_STAGE4FLAT      [INFO 1 ] skipping flattening of dark/arc/bars/direct
image


  3/ 68     13 2 2 ALL  1 10 000 Med BM   KBlu   5000.0 2458572.579   30.0
arcThAr         13  58.00000000  45.00000000     0.00  1.410

KCWI_STAGE4FLAT      [INFO 1 ] input reduced image:
/Volumes/T01/d1/keck/kcwi/raw/mar19/redux/kb190330_00013_intd.fits

KCWI_STAGE4FLAT      [INFO 1 ] flat file =
/Volumes/T01/d1/keck/kcwi/raw/mar19/redux/kb190330_00014_mflat.fits

KCWI_STAGE4FLAT      [INFO 1 ] geom file =
/Volumes/T01/d1/keck/kcwi/raw/mar19/redux/kb190330_00011_geom.fits

KCWI_STAGE4FLAT      [INFO 1 ] skipping flattening of dark/arc/bars/direct
image


  4/ 68     14 2 2 TUP  0 10 000 Med BM   KBlu   5000.0 2458572.580    1.2
cflatContin     14  58.00000000  45.00000000     0.00  1.410

KCWI_STAGE4FLAT      [INFO 1 ] input reduced image:
/Volumes/T01/d1/keck/kcwi/raw/mar19/redux/kb190330_00014_intd.fits

KCWI_STAGE4FLAT      [INFO 1 ] flat file =
/Volumes/T01/d1/keck/kcwi/raw/mar19/redux/kb190330_00014_mflat.fits

KCWI_STAGE4FLAT      [INFO 1 ] geom file =
/Volumes/T01/d1/keck/kcwi/raw/mar19/redux/kb190330_00011_geom.fits

% Compiled module: KCWI_MAKE_FLAT.

KCWI_MAKE_FLAT       [INFO 1 ] Wed Apr 24 13:11:36 2019

KCWI_MAKE_FLAT       [INFO 1 ] combining this many images:            6

% Compiled module: DJS_ITERSTAT.

% Compiled module: SPLINE_P.

% Compiled module: KCWI_BM_LEDGE_POSITION.

KCWI_MAKE_FLAT       [INFO 1 ] BM ledge calculated wavelength for ref slice
(A):    5248.27

% Subscript range values of the form low:high must be >= 0, < size, with
low <= high: DERIV.

% Execution halted at: KCWI_MAKE_FLAT    489
/Users/ebeling/soft/kcwi/KcwiDRP-master/kcwi/kcwi_make_flat.pro

%                      KCWI_STAGE4FLAT   245
/Users/ebeling/soft/kcwi/KcwiDRP-master/kcwi/kcwi_stage4flat.pro

%                      $MAIN$

I presume the "fatal" message at the beginning is in fact not fatal? The
indexing error a little later certainly is though. Have you seen this
before?

Mahalo,

Harald

**Comment by lucarizzi** [comment]
Let's verify that you are running the correct version of the code.
Did you install it using a tar file or using git?

If you used tar, I recommend that you switch to git.

> git clone https://github.com/Keck-DataReductionPipelines/KcwiDRP.git

The installation instructions might be different, but this is my recommendation. This will allow us to verify that you are running the correct version by using the command:

> git pull

If the result is that nothing needs to be downloaded, then you are on the latest version.

**Comment by hebeling** [comment]
I got the code from github, as you recommended at the time. It came in the
form of a zip file (KcwiDRP-master.zip). Entering the KcwiDRP-master
directory and typing "git pull" produces this:

[marvin:~/soft/kcwi/KcwiDRP-master] ebeling% git pull
fatal: Not a git repository (or any of the parent directories): .git

Which makes me suspect I should have got it in some other form. Doing the
"git clone" thing did not change anything though:

[marvin:~/soft] ebeling% git clone
https://github.com/Keck-DataReductionPipelines/KcwiDRP.git
Cloning into 'KcwiDRP'...
remote: Enumerating objects: 20, done.
remote: Counting objects: 100% (20/20), done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 4641 (delta 8), reused 11 (delta 4), pack-reused 4621
Receiving objects: 100% (4641/4641), 8.32 MiB | 4.89 MiB/s, done.
Resolving deltas: 100% (2548/2548), done.
Checking connectivity... done.
[marvin:~/soft] ebeling% git pull
fatal: Not a git repository (or any of the parent directories): .git

What now?

Mahalo,

Harald

**Comment by lucarizzi** [comment]
I should have been clearer

 

Before you do git pull, you have to go inside the directory that github has created, called KcwiDRP

 

So:

 

cd KcwiDRP

git pull

**Comment by hebeling** [comment]
Sorry, that was me being stupid.

[marvin:~/soft/KcwiDRP] ebeling% git pull
Already up-to-date.

I'll wipe the redux directory and start over...

Mahalo,

Harald

**Comment by lucarizzi** [comment]
Excellent.

Make sure this is the only active version of the pipeline.

 

Luca

**Comment by hebeling** [comment]
It worked! Haven't applied the flux calibration (stage 8) but no errors all
the way through Stage 7. I have not yet inspected the resulting data cubes,
but I am optimistic.

Thanks for your help!

Aloha,

Harald
