### ISSUE TITLE
Clarification on Sky Subtraction

### ISSUE THREAD

**Issue by vivian-u** [Keck-DataReductionPipelines/KcwiDRP#4]
Hello, I am a little confused about how exactly or whether to run the Stage5sky step. I have observed three difference science targets whose extended emission warranted separate sky frames for each. According to the AAAREADME file, I would need to input said sky frames as the sky master in the kcwi.proc file. (I presume these would be the *_intf.fits versions, or the *_sky.fits files? Would the latter be generated if stage5 wasn't run?) But more importantly, the readme file also said that this step should be skipped if the sky is not well sampled in the frame or is mixed with a large fraction of object light. So should stage5 be run with the separate sky frames specified in the kcwi.proc, or not? Or would stage6cube just generate separate sky cubes if they're correctly identified in the kcwi.proc file (after stage 5 is skipped)? Thank you for any pointer in advance.

**Comment by scizen9** [comment]
You would edit kcwi.proc and change the mastersky keyword to point at the relevant sky frame and then run stage5.  When your object frame gets processed, it will generate the sky from the sky frame and apply it to the object frame.
